# server port config
server:
  port: 8002

# datasource config
spring: 
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: C##LOGIN_AUTH
    password: LOGIN_AUTH
 
# mybatis config
mybatis : 
  mapper-locations : mappers/**/*.xml